= Aggiungi attività manuale
:allow-uri-read: 




=== Aggiungi attività manuale

Affinché uno script nel repository possa eseguire qualsiasi azione, è necessario creare un'attività per associare tale script a un trigger selezionato. In questo esempio, l'attività viene eseguita quando l'amministratore VDS attiva manualmente lo script.

Gli eventi con script VDS offrono molti altri tipi di trigger di attività, come _Create Server_, che possono essere utilizzati come alternativa al tipo di evento _Manual_. L'utilizzo di _Create Server_ eseguirebbe semplicemente questo script su tutte le macchine virtuali appena create in VDS. _Create Server_ e altri trigger sono documentati e possono essere esplorati link:Management.Scripted_Events.scripted_events.html["qui"].

.Per creare un'attività e collegare questo script a un'azione:
. Accedere alla sezione Scripted Events (Eventi con script) in VDS
. In _attività_, fare clic su _+ Aggiungi attività_
. Nella finestra di dialogo aperta, immettere le seguenti informazioni:
+
** *Nome:* assegnare un nome all'attività
** *Descrizione:* se si desidera, inserire una descrizione
** *Implementazione* selezionare l'implementazione desiderata dal menu a discesa
** *Script:* selezionare lo script di installazione (o disinstallazione) dal menu a discesa. Questo potrebbe essere lo script globale o lo script cliente che hai clonato e personalizzato.
** *Argomenti:* lasciare vuoto
** *Casella di controllo abilitata:* `Check` la scatola
** *Tipo di evento:* selezionare `Manual` dal menu a discesa
** *Target Type:* selezionare `Servers` pulsante di opzione
** *Server gestiti:* `Check` La casella per ciascuna macchina virtuale che deve ricevere questa disinstallazione.



