= Aggiungere l'attività di installazione/disinstallazione dell'applicazione
:allow-uri-read: 




=== Aggiungere l'attività di installazione/disinstallazione dell'applicazione

Affinché uno script nel repository possa eseguire qualsiasi azione, è necessario creare un'attività per associare tale script a un trigger selezionato. In questo esempio, l'attività installerà/disinstallerà l'applicazione quando questa viene aggiunta o rimossa dall'area di lavoro (dalla pagina _Workspace > Applications_ in VDS).

Gli eventi con script VDS offrono molti altri tipi di trigger di attività, come _Create Server_, che possono essere utilizzati come alternativa al tipo di evento _Application Install_ (o _Application Uninstall_). L'utilizzo di _Create Server_ eseguirebbe semplicemente l'installazione dell'applicazione su tutte le macchine virtuali appena create in VDS. _Create Server_ e altri trigger sono documentati e possono essere esplorati link:Management.Scripted_Events.scripted_events.html["qui"].


NOTE: Questa applicazione deve essere presente nella libreria di applicazioni VDS. Questo link:Management.Applications.application_entitlement_workflow.html#add-applications-to-the-app-catalog["sezione"] Del diritto all'applicazione per RDS, l'articolo illustra l'aggiunta di applicazioni alla libreria.

.Per creare un'attività e collegare questo script a un'azione:
. Accedere alla sezione _Scripted Events_ in VDS
. In _attività_, fare clic su _+ Aggiungi attività_
. Nella finestra di dialogo aperta, immettere le seguenti informazioni:
+
** *Nome:* assegnare un nome all'attività
** *Descrizione:* se si desidera, inserire una descrizione
** *Implementazione* selezionare l'implementazione desiderata dal menu a discesa
** *Script:* selezionare lo script di installazione (o disinstallazione) dal menu a discesa. Questo potrebbe essere lo script globale o lo script cliente che hai clonato e personalizzato.
** *Argomenti:* lasciare vuoto
** *Casella di controllo abilitata:* `Check` la scatola
** *Tipo di evento:* selezionare `Application Install` (O disinstallazione applicazione) dal menu a discesa
** *Applicazione:* selezionare questa applicazione dal menu a discesa
** *Percorso di scelta rapida:* inserire il percorso di scelta rapida predefinito per questa applicazione (indicato sopra)



